services:
  db:
    container_name: db
    image: mariadb:11.5.2
    restart: always
    ports: 
      - 23306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=4321
    networks:
      myNet:
        ipv4_address: 192.168.100.10

networks:
  myNet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.254